### ISSUE TITLE
Bonus pickup issues

### ISSUE THREAD

**Issue by rbandboy** [nhydock/Storymode#12]
During a file explore, bonuses occur occasionally from fallen corpses.  Approach them, and they disappear.

Or one would hope.  When you approach at an angle, then move into the orthogonal square, the powerup fails to recognize your approach.

**Comment by nhydock** [comment]
It appeared to be a problem with the collision detection.  I fixed some things up and the error stopped happening from my testing.  An update has just been pushed, please make sure the issue has been resolved before closing.
