### ISSUE TITLE
AppHangB1 on game launch.

### ISSUE THREAD

**Issue by Xial** [nhydock/Storymode#13]
Attempting to launch the game through Steam yields the game hanging at launch, and input with keyboard or mouse causes the window to change to the milky white "not responding" color that Windows assigns to applications that have hung for some reason.

Environment is:
Windows 10 Pro x64 on AMD FX-6100 Six-Core processor, 16 GB RAM, with an AMD Radeon R9 270x GPU.

Reproduction steps:
Launch game from Steam.
The game will freeze on the Thank you screen with no interaction. Pressing any buttons will reveal that the game has frozen.
Close the game, and ensure that the Steam Overlay is disabled.
Relaunch the game with the overlay disabled.
Also attempt to launch the game from the batch file in the directory.
![storymode-hang](https://cloud.githubusercontent.com/assets/31123/10154393/8b4a35dc-661b-11e5-8d5d-be47a171bbfc.png)

No log file or stack trace is generated at any point.
The system's event viewer reveals the only information I can find, showing the AppHangB1 there.

**Comment by nhydock** [comment]
The JRE that is packed with StoryMode is a 64-bit JRE for Windows.  For an AppHangB1 to occur, it is typically an error with either graphics drivers or JRE.  Try running Storymode with the i586 JRE for Windows from https://github.com/alexkasko/openjdk-unofficial-builds to see if that fixes things for you.

**Comment by Xial** [comment]
Just tried it with the i586 JRE here to see if I could get a different result, but it results in the same behavior from earlier, with the Steam Overlay disabled.

I then went on to do the following:

* Removed existing graphics driver, installed beta driver, and restarted. 
  * Attempt to launch game, but reproduced same hangs.
* Removed beta driver, returned to latest released driver, restarted. 
  * Attempted to launch game with the default JRE that shipped, but hangs. 
* Tried launching with the 32-bit i586 version of the JRE.
  * Game hangs at the screen pictured above.
* Tried with 64-bit Java 8 JRE from Oracle.
  * Game hangs at the screen pictured above.

System event logs show only the _AppHangB1_ in each instance.

Ran Nir Sofer's [WhatIsHang](http://nirsoft.net/utils/what_is_hang.html) to see if I could find any clues, and it returned the following:

> Remarks:
> * The program probably hangs because there is an infinite loop, very long loop, or recursive calls.

Each run of the WhatIsHang application is accompanied by a log file, but I'm not certain if the logs generated by this would be of use.

**Comment by nhydock** [comment]
Wouldn't hurt posting the WhatIsHang log.  Upload it to gist or pastebin and link it here

**Comment by Xial** [comment]
https://gist.github.com/Xial/3511e0deb4bbb9c5f1a6#file-sm-ojdk-as-shipped-txt

https://gist.github.com/Xial/3511e0deb4bbb9c5f1a6#file-sm-ojdk-i586-txt

https://gist.github.com/Xial/3511e0deb4bbb9c5f1a6#file-sm-java8-txt

I apologize, I'm not as familiar with Git and its gists, but I do have each of the logs uploaded, in the order of the JRE that shipped with the game, the i586 JRE that I tried, and finally, the Java 8 JRE. Thanks for your time! :)

**Comment by nhydock** [comment]
It appears to be crashing due to Steamworks4j and fetching information from Steam.  I'm using an old version with StoryMode, so I'll update it to see if that fixes the problem.

**Comment by Xial** [comment]
Just grabbed the update that appeared on Steam. I'm able to load and run the game now in its default configuration.  :+1:
