### ISSUE TITLE
Got a problem with Steam

### ISSUE THREAD

**Issue by DonDac** [nhydock/Storymode#14]
Hi I just got your Game on Steam. Its only downloading the Gamefolder but no Files could you please help me.

**Comment by nhydock** [comment]
Are you trying to play on Linux?

I'm having the same problem on Linux but not Windows.  It's odd as the depot set up entirely and definitely has files in it according to Steamworks.  I'm wondering if there's a problem with the Linux steam client right now.

**Comment by nhydock** [comment]
I think the problem might have been with how I had the linux depot set to 64-bit only.  The openjdk packaged with the game is 64-bit, so I thought it would be safe to set the depot to 64-bit only.  I don't know if Steam on linux is able to detect the architecture though, as it's a 32-bit binary.  I changed the depot to all architectures so maybe now it will download properly.  

Please test to see if this solves the problem for you.  I'm currently away from my development computer so I can't test it myself.

**Comment by DonDac** [comment]
hi no its no linux based pc. I´m sorry it´s windows and gets denied

**Comment by DonDac** [comment]
even the Steam Repair tool just writes no errors detected on the game

**Comment by nhydock** [comment]
This appears to just be a problem with steam for games every now and then.  Work arounds are always really weird.  Recommendations range from running the steam verify cache, to uninstalling steam, to manually setting the game's language, or changing the server that games are downloaded from.

**Comment by DonDac** [comment]
ok I´ll try that thank you very much for your support and fast awnsers!
