### ISSUE TITLE
Impossible to complete quests

### ISSUE THREAD

**Issue by de-ko** [nhydock/Storymode#20]
I've accepted some quest, completed the requirements, but when I go to town, hitting "Complete Quest" button does nothing.
See the attached screenshot.

BTW, the quest lists are a mess: accepted quest re-appear in available quests after character re-enters the town.
![storymode_quest_bug](https://cloud.githubusercontent.com/assets/18178186/14230330/5b8be02c-f917-11e5-93de-9df60ec414f3.jpg)

**Comment by nhydock** [comment]
Fix will be pushed in a moment.  It was thankfully just a bug with the ui and not the entire quest logic.
