### ISSUE TITLE
Logic for "My List"/"Today's Crafts" appears to be backwards, with respect to day advancement.

### ISSUE THREAD

**Issue by Reassembly** [nhydock/Storymode#22]
When a day is advanced by choosing "Rest", the "My List" crafting list is refreshed with a new set of five crafting recipes, while the "Today's Crafts"/"Today's Special" crafting list (name inconsistent in UI!) remains a static list of two recipes, unchanged by advancing the day.

**Comment by nhydock** [comment]
Thank you for the report, I'll get this fixed with the feature patch I'll be pushing this weekend.

**Comment by nhydock** [comment]
Issue has been resolved as of yesterday's update
